# Generated by Django 3.0.5 on 2020-04-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала эксплуатации')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50, verbose_name='Производитель')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50, verbose_name='Производитель')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование услуги')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата услуги')),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('invoice_num', models.CharField(blank=True, max_length=15, verbose_name='Номер счета')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счета')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Cartridge', verbose_name='Картридж')),
                ('servise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Service', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Имя устройства')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата изготовления')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала эксплуатации')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.DeviceModel', verbose_name='Модель устройства')),
            ],
        ),
        migrations.AddField(
            model_name='cartridge',
            name='cartridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.CartridgeModel', verbose_name='Модель картриджа'),
        ),
    ]
