# Generated by Django 3.0.5 on 2020-04-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carefreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providedservices',
            old_name='servise',
            new_name='service',
        ),
    ]
