# Generated by Django 3.0.5 on 2020-04-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carefreg', '0002_auto_20200414_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='Наименование отдела')),
                ('abbreviated_name', models.CharField(max_length=3, unique=True, verbose_name='Сокращенное наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание устройства'),
        ),
        migrations.AlterField(
            model_name='providedservices',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
