# Generated by Django 3.0.5 on 2020-04-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carefreg', '0003_auto_20200420_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='abbreviated_name',
            field=models.CharField(max_length=3, unique=True, verbose_name='Аббревиатура'),
        ),
        migrations.CreateModel(
            name='RelDeviceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=150, verbose_name='Комментарий')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Device', verbose_name='Устройство')),
                ('owner_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Department', verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='RelCartridgeDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=150, verbose_name='Комментарий')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Cartridge', verbose_name='Картридж')),
                ('owner_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carefreg.Device', verbose_name='Устройство')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reldevicedepartment',
            constraint=models.UniqueConstraint(fields=('rel_date', 'device'), name='rel_device_department__unique_date_device'),
        ),
        migrations.AddConstraint(
            model_name='reldevicedepartment',
            constraint=models.UniqueConstraint(fields=('rel_date', 'device', 'owner_dept'), name='rel_device_department__unique_date_device_owner_dept'),
        ),
        migrations.AddConstraint(
            model_name='relcartridgedevice',
            constraint=models.UniqueConstraint(fields=('rel_date', 'cartridge'), name='rel_cartridge_device__unique_date_cartridge'),
        ),
        migrations.AddConstraint(
            model_name='relcartridgedevice',
            constraint=models.UniqueConstraint(fields=('rel_date', 'cartridge', 'owner_device'), name='rel_cartridge_device__unique_date_cartridge_owner_device'),
        ),
    ]
