# Generated by Django 3.0.5 on 2020-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carefreg', '0004_auto_20200422_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджи'},
        ),
        migrations.AlterModelOptions(
            name='cartridgemodel',
            options={'verbose_name': 'Модель картриджа', 'verbose_name_plural': 'Модели картриджей'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'verbose_name': 'Модель устройства', 'verbose_name_plural': 'Модели устройств'},
        ),
        migrations.AlterModelOptions(
            name='providedservices',
            options={'ordering': ('-service_date',), 'verbose_name': 'Предоставленные услуги', 'verbose_name_plural': 'Предоставленная услуга'},
        ),
        migrations.AlterModelOptions(
            name='relcartridgedevice',
            options={'ordering': ('-rel_date',), 'verbose_name': 'Принадлежность картриджа устройству', 'verbose_name_plural': 'Принадлежности картриджей устройствам'},
        ),
        migrations.AlterModelOptions(
            name='reldevicedepartment',
            options={'ordering': ('-rel_date',), 'verbose_name': 'Принадлежность устройства отделу', 'verbose_name_plural': 'Принадлежности устройств отделам'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='cartridge',
            name='device',
            field=models.ManyToManyField(related_name='cartridges', through='carefreg.RelCartridgeDevice', to='carefreg.Device'),
        ),
    ]
