# Generated by Django 3.0.5 on 2020-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carefreg', '0005_auto_20200507_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.ManyToManyField(related_name='devices', through='carefreg.RelDeviceDepartment', to='carefreg.Department'),
        ),
    ]
